# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interface0.0.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from __init__ import OS
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QPlainTextEdit
import os
scriptDir = os.path.dirname(os.path.realpath(__file__))
class FileEdit(QPlainTextEdit):
    def __init__(self, parent):
        super(FileEdit, self).__init__(parent)
    def dragEnterEvent(self, event):
        data = event.mimeData()
        urls = data.urls()
        if urls and urls[0].scheme() == 'file':
            event.acceptProposedAction()

    def dragMoveEvent(self, event):
        data = event.mimeData()
        urls = data.urls()
        if urls and urls[0].scheme() == 'file':
            event.acceptProposedAction()

    def dropEvent(self, event):
        data = event.mimeData()
        urls = data.urls()
        if urls and urls[0].scheme() == 'file':
            filepath = str(urls[0].path())[1:]
            # any file type here
            if filepath[-4:] == ".txt":
                filepath = "/"+filepath if OS == "Linux" or OS == "MacOS" else filepath
                text = open(filepath, 'r', encoding="utf-8").read()
                self.setPlainText(text)
            else:
                dialog = QMessageBox()
                dialog.setWindowTitle("Қате: жарамсыз файл")
                dialog.setText("Тек .txt файлдары қабылданады")
                dialog.setIcon(QMessageBox.Warning)
                dialog.exec_()
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 620)
        self.basewidth = 1040
        self.expandwidth = 360
        self.tbasewidth = 0
        self.texpandwidth = 600
        self.tbasex = 1050
        self.texpandx = 450
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1060, 560))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.plainTextEdit = FileEdit(self.frame)#QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 30, 1040, 430))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(445, 495, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(495, 495, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setVisible(False)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 495, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_2")
        self.pushButton_3.setVisible(False)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(470, 10, 80, 20))
        self.label_2.setVisible(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(1050, 30, 0, 430))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(26)
        self.tableWidget.setRowCount(100)
        header = self.tableWidget.horizontalHeader()    
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(20, 480, 1030, 30))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = self.menubar.addMenu("Файл")
        self.editMenu = self.menubar.addMenu("Өңдеу")
        self.helpMenu = self.menubar.addMenu("Көмек")
        self.actiontfidf = QtWidgets.QAction(MainWindow)
        self.actiontfidf.setObjectName("actiontfidf")
        self.actionAboutUs = QtWidgets.QAction(MainWindow)
        self.actionAboutUs.setObjectName("actionAboutUs")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSelectAll = QtWidgets.QAction(MainWindow)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.actionClearAll = QtWidgets.QAction(MainWindow)
        self.actionClearAll.setObjectName("actionClearAll")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.fileMenu.addAction(self.actionOpen)
        self.fileMenu.addAction(self.actionSave)
        self.fileMenu.addAction(self.actionExit)
        self.editMenu.addAction(self.actionSelectAll)
        self.editMenu.addAction(self.actionClearAll)
        self.helpMenu.addAction(self.actionAboutUs)
        self.helpMenu.addAction(self.actiontfidf)
        
        self.pushButton_2.clicked.connect(self.resetclick)
        self.actiontfidf.triggered.connect(self.clicktfidf)
        self.actionClearAll.triggered.connect(self.clearplt)
        self.actionExit.triggered.connect(lambda self: QtWidgets.QApplication.quit())
        self.retranslateUi(MainWindow)
        MainWindow.setWindowIcon(QtGui.QIcon(scriptDir + os.path.sep + 'pp.jpg'))
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def exit(self):
        QtWidgets.QApplication.quit()
    def clearplt(self):
        self.plainTextEdit.clear()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Кілттік сөз"))
        MainWindow.setWindowIcon(QtGui.QIcon("pp.jpeg"))
        self.plainTextEdit.setPlaceholderText(_translate("MainWindow", "Мәтінді осында еңгізіңіз... немесе құжатты осында сүйреңіз"))
        self.pushButton.setText(_translate("MainWindow", "Бастау"))
        self.pushButton_2.setText(_translate("MainWindow", "Жаңарту"))
        self.pushButton_3.setText(_translate("MainWindow", "Қайта есептеу"))
        self.label.setText(_translate("MainWindow", "Мәтін"))
        self.label_2.setText(_translate("MainWindow", "Нәтижесі"))
        self.actiontfidf.setText(_translate("MainWindow", "TF-IDF"))
        self.actiontfidf.setShortcut("Ctrl+?")
        self.actionAboutUs.setText(_translate("MainWindow", "Біз жайлы"))
        self.actionAboutUs.setShortcut("Ctrl+H")
        self.actionOpen.setText(_translate("MainWindow", "Ашу"))
        self.actionOpen.setShortcut("Ctrl+O")
        self.actionSave.setText(_translate("MainWindow", "Сақтау"))
        self.actionSave.setShortcut("Ctrl+S")
        self.actionExit.setText(_translate("MainWindow", "Шығу"))
        self.actionExit.setShortcut("Escape")
        self.actionSelectAll.setShortcut("Ctrl+A")
        self.actionSelectAll.setText(_translate("MainWindow", "Барлығын белгілеу"))
        self.actionClearAll.setText(_translate("MainWindow", "Жолды жаңарту"))
    def resetclick(self):
        self.pushButton.setVisible(True)
        self.pushButton_2.setVisible(False)
        self.pushButton_3.setVisible(False)
        self.plainTextEdit.clear()
        self.tableWidget.clear()
        self.resizewin()
        self.label_2.setVisible(False)
        self.progressBar.setVisible(False)
    def clicktfidf(self):
        dialog = QMessageBox()
        dialog.setWindowTitle("TF-IDF жайлы қысқаша мәлімет!!!")
        dialog.setText("""
    TF-IDF (ағылшын тілінен аударғанда TF - мерзімділік жиілігі, IDF - кері құжат жиілігі) - бұл құжат жиынтығы немесе корпусының бөлігі болып табылатын құжат контекстіндегі сөздің маңыздылығын бағалау үшін қолданылатын статистикалық шара. Сөздің салмағы құжаттағы осы сөздің қолданылу жиілігіне пропорционалды және жинақтың барлық құжаттарындағы сөздің қолданылу жиілігіне кері пропорционалды.

[Мысал]
    Егер құжат 100 сөзден тұрса және онда «қоян» сөзі 3 рет кездессе, онда құжаттағы «қоян» сөзінің жиілігі (TF) 0,03 (3/100) болады. IDF-ті барлық құжаттар санының «қоян» сөзі бар құжаттар санына қатынасының ондық логарифмі ретінде есептейік. Сонымен, егер «қоян» 1000000 құжаттың 1000 құжатында болса, онда IDF келесідей болады: журнал (10.000.000 / 1000) = 4. Салмақ сөзінің соңғы мәнін есептеу үшін TF IDF-ге көбейтілуі керек. Бұл мысалда таңдалған құжаттағы «қоян» сөзі үшін TF-IDF мәні келесідей болады: 0,03 × 4 = 0,12.

""")
        dialog.setStandardButtons(QMessageBox.Ok)
        dialog.setIcon(QMessageBox.Information)
        dialog.exec_()
    def rettext(self):
        return self.plainTextEdit.toPlainText()
    def clearbar(self):
        self.progressBar.setVisible(False)
        self.pushButton_2.setVisible(True)
        self.pushButton_3.setVisible(True)
    def tabledsgn(self):
        _translate = QtCore.QCoreApplication.translate
        letters = "a b c d e f g h i j k l m n o p q r s t u v w x y z".upper()
        letters = letters.split(' ')
        for i in range(26):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(i, item)  
            itemt = self.tableWidget.horizontalHeaderItem(i)
            itemt.setText(_translate("MainWindow", letters[i])) 
        for i in range(100):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
            itemt = self.tableWidget.verticalHeaderItem(i)
            itemt.setText(_translate("MainWindow", str(i+1)))
        self.tableWidget.setSpan(0, 0, 1, 2)
        self.tableWidget.setSpan(0, 2, 1, 2)
        self.tableWidget.setSpan(0, 4, 1, 2)
        mas = ["TF", "IDF", "TF-IDF"]
        row = 0
        col = 0
        i = 0
        while col < 5:
            item = QtWidgets.QTableWidgetItem()
            item.setTextAlignment(QtCore.Qt.AlignCenter)
            item.setBackground(QtGui.QColor("Lime"))
            item.setText(mas[i])
            self.tableWidget.setItem(row, col, item)
            col += 2
            i += 1
        #192, 254, 255
    def resizewin(self):
        currentwidth = self.plainTextEdit.width()
        basewidth = int()
        expandwidth = int()
        if self.basewidth == currentwidth:
            basewidth = self.basewidth
            expandwidth = self.expandwidth
        else:
            basewidth = self.expandwidth
            expandwidth = self.basewidth
        self.animation = QtCore.QPropertyAnimation(self.plainTextEdit, b'geometry')
        self.animation.setDuration(800)
        self.animation.setStartValue(QtCore.QRect(10, 30, basewidth, 430))
        self.animation.setEndValue(QtCore.QRect(10, 30, expandwidth, 430))
        self.animation.start()
        tcurrentwidth = self.tableWidget.width()
        tcurrentx = self.tableWidget.x()
        tbasewidth = int()
        texpandwidth = int()
        tbasex = int()
        texpandx = int()
        if tcurrentwidth == self.tbasewidth and tcurrentx == self.tbasex:
            tbasewidth = self.tbasewidth
            tbasex = self.tbasex
            texpandwidth = self.texpandwidth
            texpandx = self.texpandx
        else:
            tbasewidth = self.texpandwidth
            tbasex = self.texpandx
            texpandwidth = self.tbasewidth
            texpandx = self.tbasex
        self.animation1 = QtCore.QPropertyAnimation(self.tableWidget, b'geometry')
        self.animation1.setDuration(800)
        self.animation1.setStartValue(QtCore.QRect(tbasex, 30, tbasewidth, 430))
        self.animation1.setEndValue(QtCore.QRect(texpandx, 30, texpandwidth, 430))
        self.animation1.start()
