# Generated by Django 3.1.4 on 2021-06-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': False, 'verbose_name': 'Authorization group', 'verbose_name_plural': 'Authorization groups'},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': False, 'verbose_name': 'Authorization group permission', 'verbose_name_plural': 'Authorization group permissions'},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': False, 'verbose_name': 'Authorization permission', 'verbose_name_plural': 'Authorization permissions'},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False, 'verbose_name': 'Authorization user', 'verbose_name_plural': 'Authorization users'},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': False, 'verbose_name': 'Authorization user group', 'verbose_name_plural': 'Authorization user groups'},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': False, 'verbose_name': 'Authorization user permission', 'verbose_name_plural': 'Authorization user permissions'},
        ),
        migrations.AlterModelOptions(
            name='corpora',
            options={'managed': False, 'ordering': ['-id'], 'verbose_name': 'Corpora', 'verbose_name_plural': 'Corpora'},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': False, 'verbose_name': 'Django admin log', 'verbose_name_plural': 'Django admin logs'},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={'managed': False, 'verbose_name': 'Django content type', 'verbose_name_plural': 'Django content types'},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': False, 'verbose_name': 'Django migration', 'verbose_name_plural': 'Django migrations'},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': False, 'verbose_name': 'Django session', 'verbose_name_plural': 'Django sessions'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'managed': False, 'ordering': ['-kz'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
