# Generated by Django 3.1.4 on 2021-06-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210612_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'managed': False, 'ordering': ['kz'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
